/* eslint-disable */
/* global WebImporter */

// Generic WKND import script. One script drives every template: the template
// whose urls[] contains the page being imported is selected at runtime from the
// embedded PAGE_TEMPLATES snapshot, and its block mappings drive parser dispatch.

// PARSER IMPORTS (all block variants used across templates)
import carouselParser from './parsers/carousel.js';
import columnsParser from './parsers/columns.js';
import heroParser from './parsers/hero.js';
import cardsParser from './parsers/cards.js';
import tabsParser from './parsers/tabs.js';
import accordionParser from './parsers/accordion.js';

// TRANSFORMER IMPORTS
import wkndCleanupTransformer from './transformers/wknd-cleanup.js';

// PARSER REGISTRY
const parsers = {
  carousel: carouselParser,
  columns: columnsParser,
  hero: heroParser,
  cards: cardsParser,
  tabs: tabsParser,
  accordion: accordionParser,
};

// TRANSFORMER REGISTRY
const transformers = [wkndCleanupTransformer];

// PAGE TEMPLATES SNAPSHOT (embedded from tools/importer/page-templates.json).
// Regenerated by scripts/sync-templates-snapshot.js before each bundle so the
// browser importer needs no fs access.
/* WKND_TEMPLATES_SNAPSHOT_START */
const PAGE_TEMPLATES = {"templates":[{"name":"card-listing","urls":["https://wknd.site/us/en/about-us.html","https://wknd.site/us/en/magazine.html"],"blocks":[{"name":"columns","instances":[".teaser.cmp-teaser--featured"]},{"name":"cards","instances":[".image-list.list",".experiencefragment.cmp-experience-fragment--contributor"]}]},{"name":"adventure-detail","urls":["https://wknd.site/us/en/adventures/bali-surf-camp.html","https://wknd.site/us/en/adventures/beervana-portland.html","https://wknd.site/us/en/adventures/climbing-new-zealand.html","https://wknd.site/us/en/adventures/colorado-rock-climbing.html","https://wknd.site/us/en/adventures/cycling-southern-utah.html","https://wknd.site/us/en/adventures/cycling-tuscany.html","https://wknd.site/us/en/adventures/downhill-skiing-wyoming.html","https://wknd.site/us/en/adventures/gastronomic-marais-tour.html","https://wknd.site/us/en/adventures/napa-wine-tasting.html","https://wknd.site/us/en/adventures/riverside-camping-australia.html","https://wknd.site/us/en/adventures/ski-touring-mont-blanc.html","https://wknd.site/us/en/adventures/surf-camp-costa-rica.html","https://wknd.site/us/en/adventures/tahoe-skiing.html","https://wknd.site/us/en/adventures/west-coast-cycling.html","https://wknd.site/us/en/adventures/whistler-mountain-biking.html","https://wknd.site/us/en/adventures/yosemite-backpacking.html"],"blocks":[{"name":"hero","instances":[".carousel.cmp-carousel--mini"]},{"name":"columns","instances":[".contentfragment.cmp-contentfragment--elements"]},{"name":"tabs","instances":[".tabs.panelcontainer",".cmp-tabs"]}]},{"name":"adventure-listing","urls":["https://wknd.site/us/en/adventures.html"],"blocks":[{"name":"hero","instances":[".teaser.cmp-teaser--hero"]},{"name":"cards","instances":[".cmp-tabs__tabpanel--active ul.cmp-image-list"]}]},{"name":"faq-accordion","urls":["https://wknd.site/us/en/faqs.html"],"blocks":[{"name":"accordion","instances":[".accordion.cmp-accordion",".cmp-accordion"]}]},{"name":"homepage","urls":["https://wknd.site/us/en.html"],"blocks":[{"name":"carousel","instances":[".carousel.cmp-carousel--hero","div.carousel.panelcontainer"]},{"name":"columns","instances":[".teaser.cmp-teaser--featured"]},{"name":"hero","instances":[".teaser.cmp-teaser--hero.cmp-teaser--imagebottom"]},{"name":"cards","instances":[".image-list.list"]}]},{"name":"article-detail","urls":["https://wknd.site/us/en/magazine/arctic-surfing.html","https://wknd.site/us/en/magazine/guide-la-skateparks.html","https://wknd.site/us/en/magazine/san-diego-surf.html","https://wknd.site/us/en/magazine/ski-touring.html","https://wknd.site/us/en/magazine/western-australia.html"],"blocks":[]}]};
/* WKND_TEMPLATES_SNAPSHOT_END */

function normalizeUrl(u) {
  try {
    const url = new URL(u);
    return `${url.origin}${url.pathname}`.replace(/\/$/, '');
  } catch (e) {
    return u;
  }
}

/**
 * Select the template whose urls[] contains the page being imported.
 */
function selectTemplate(originalUrl) {
  const target = normalizeUrl(originalUrl);
  const templates = PAGE_TEMPLATES.templates || [];
  const match = templates.find((t) => (t.urls || []).some((u) => normalizeUrl(u) === target));
  return match || null;
}

/**
 * Find all blocks on the page based on the selected template configuration.
 * De-duplicates elements matched by more than one selector.
 */
function findBlocksOnPage(document, template) {
  const pageBlocks = [];
  const seen = new Set();
  (template.blocks || []).forEach((blockDef) => {
    (blockDef.instances || []).forEach((selector) => {
      let elements = [];
      try {
        elements = document.querySelectorAll(selector);
      } catch (e) {
        elements = [];
      }
      elements.forEach((element) => {
        if (seen.has(element)) return;
        seen.add(element);
        pageBlocks.push({ name: blockDef.name, selector, element });
      });
    });
  });
  return pageBlocks;
}

function executeTransformers(hookName, element, payload, template) {
  const enhancedPayload = { ...payload, template };
  transformers.forEach((transformerFn) => {
    try {
      transformerFn.call(null, hookName, element, enhancedPayload);
    } catch (e) {
      console.error(`Transformer failed at ${hookName}:`, e);
    }
  });
}

/**
 * Map the /us/en subtree onto EDS root:
 *   /us/en.html      -> /index (root; guarded to avoid the importer empty-path crash)
 *   /us/en/<p>.html  -> /<p>
 */
function documentPath(originalUrl) {
  const raw = new URL(originalUrl).pathname
    .replace(/^\/us\/en(?=\/|\.html?$|$)/, '')
    .replace(/\/$/, '')
    .replace(/\.html?$/, '');
  return WebImporter.FileUtils.sanitizePath(raw === '' ? '/index' : raw);
}

export default {
  transform: (payload) => {
    const {
      document, url, html, params,
    } = payload;
    const main = document.body;

    const template = selectTemplate(params.originalURL) || { name: 'unknown', blocks: [] };

    // 1. beforeTransform (initial cleanup)
    executeTransformers('beforeTransform', main, payload, template);

    // 2. Find + parse blocks defined in the selected template
    const pageBlocks = findBlocksOnPage(document, template);
    pageBlocks.forEach((block) => {
      if (!block.element.parentNode) return;
      const parser = parsers[block.name];
      if (parser) {
        try {
          parser(block.element, { document, url, params });
        } catch (e) {
          console.error(`Failed to parse ${block.name} (${block.selector}):`, e);
        }
      }
    });

    // 3. afterTransform (final cleanup + internal link rewriting)
    executeTransformers('afterTransform', main, payload, template);

    // 4. WebImporter built-in rules
    const hr = document.createElement('hr');
    main.appendChild(hr);
    WebImporter.rules.createMetadata(main, document);
    WebImporter.rules.transformBackgroundImages(main, document);
    WebImporter.rules.adjustImageUrls(main, url, params.originalURL);

    return [{
      element: main,
      path: documentPath(params.originalURL),
      report: {
        title: document.title,
        template: template.name,
        blocks: pageBlocks.map((b) => b.name),
      },
    }];
  },
};
